### ISSUE TITLE
Add tslint to normalize the code format

### ISSUE THREAD

**Issue by jdneo** [jumattos/lsif-util#8] opened 2019-03-26 02:57 UTC

**Comment by jumattos** [comment] 2019-03-26 20:09
This is a good suggestion. I wrote this code a bit too quickly, and I think some refactoring/cleaning up is needed. Will work on that.

**Comment by jumattos** [comment] 2019-03-29 01:01
It took me a whole afternoon, but I just merged PR #14, adding TSLint and doing the necessary code cleanup to adequate to it. I do think the code is much clearer now, but since I don't have any unit tests set up, I am not a 100% sure this refactor didn't introduce any regressions. Let me know if you encounter any errors!

**Closed as completed by jumattos** 2019-03-29 01:01 UTC

**Comment by jdneo** [comment] 2019-03-29 01:35
Cool, thank you @jumattos!
